environments:
  devel:
    values:
      - charts:
          versions:
            muffinCurrency: 0.1.0
            muffinWallet: 0.1.0
            muffinCommon: 0.1.0
            grafana: 10.5.15
            loki: 6.51.0
            alloy: 1.5.1
      - global:
          appDomain: bighw.com
          grafanaDomain: grafana.local
          zipkinDomain: zipkin.local
          lokiUrl:  http://loki-gateway.logging.svc.cluster.local
          zipkinUrl: http://zipkin.tracing.svc.cluster.local:9411
          prometheusUrl: http://prometheus.istio-system.svc.cluster.local:9090
---
releases:
  - name: muffin-common
    namespace: bighw
    labels:
      app: muffin-common
    wait: true
    chart: ./muffin-common
    version: "{{ .Values.charts.versions.muffinCommon }}"
    values:
      - envs/{{ .Environment.Name }}/values/muffin-common.yaml.gotmpl
  - name: muffin-currency
    namespace: bighw
    labels:
      app: muffin-currency
    wait: true
    chart: ./muffin-currency
    version: "{{ .Values.charts.versions.muffinCurrency }}"
    values:
      - envs/{{ .Environment.Name }}/values/muffin-currency.yaml.gotmpl
    needs:
      - muffin-common
  - name: muffin-wallet
    namespace: bighw
    labels:
      app: muffin-wallet
    wait: true
    chart: ./muffin-wallet
    version: "{{ .Values.charts.versions.muffinWallet }}"
    needs:
      - muffin-currency
      - muffin-common
    values:
      - envs/{{ .Environment.Name }}/values/muffin-wallet.yaml.gotmpl
  - name: loki
    namespace: logging
    chart: grafana/loki
    version: "{{ .Values.charts.versions.loki }}"
    values:
      - envs/{{ .Environment.Name }}/values/loki-values.yaml
  - name: grafana
    namespace: logging
    chart: grafana/grafana
    version: "{{ .Values.charts.versions.grafana }}"
    values:
      - envs/{{ .Environment.Name }}/values/grafana-values.yaml.gotmpl