apiVersion: v1
kind: Secret
metadata:
  name: muffin-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "files/cert.pem" | b64enc }}
  tls.key: {{ .Files.Get "files/private_key.pem" | b64enc }}
