apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
spec:
  hosts:
  {{- range .Values.virtualService.hosts }}
  - {{ . | quote }}
  {{- end }}
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: "{{ include "muffin-wallet.fullname" . }}"
        port:
          number: {{ .Values.service.port }}
    timeout: {{ .Values.virtualService.http.timeout }}
    retries:
      attempts: {{ .Values.virtualService.http.retries.attempts }}
      perTryTimeout: {{ .Values.virtualService.http.retries.perTryTimeout }}
      retryOn: {{ .Values.virtualService.http.retries.retryOn }}
