apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
spec:
  hosts:
  - "bighw.com"
  gateways:
  - muffin-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: "{{ include "muffin-wallet.fullname" . }}"
        port:
          number: {{ .Values.service.port }}
